name: Facebook Live Streamer

on:
  workflow_dispatch:

jobs:
  live-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Latest FFmpeg (Official)
        run: sudo snap install ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Start Live Stream
        env:
          FB_STREAM_KEY: ${{ secrets.FB_STREAM_KEY }}
        run: python stream.py
